import '../styles/globals.css'
import type { AppProps } from 'next/app'
import Header from '../components/Header';
import Footer from '../components/Footer'
import Head from 'next/head';

function MyApp({ Component, pageProps }: AppProps) {
  return (
      <>
        <Head>
          <title>{"SWN's Portporlio"}</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link rel="preconnect" href="https://fonts.googleapis.com"/>
          <link rel="preconnect" href="https://fonts.gstatic.com"/>
          <link href="https://fonts.googleapis.com/css2?family=Black+Han+Sans&family=Noto+Sans+KR:wght@500&display=swap" rel="stylesheet"></link>
        </Head>
        <Header/>
        <Component {...pageProps} />
        <Footer/>
      </>
    )
}

export default MyApp
